# FROM golang:1.22.3 AS builder
# WORKDIR /usr/src/app
# COPY . .
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o order ./cmd/main.go

# FROM scratch
# COPY --from=builder /usr/src/app/order ./order
# CMD ["./order"]

FROM alpine:latest
RUN mkdir /app
COPY order /app
CMD [ "/app/order"]
