apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broker
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: broker.example.com
    http:
      paths:
      - path: /broker
        pathType: Prefix
        backend:
          service:
            name: broker
            port: 
              number: 8082
  tls:
    - hosts:
        - ingress.local