apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: "909007/broker:latest"
          imagePullPolicy:  Always
          ports:
            - containerPort: 8082
          env:
            - name: APPLICATION_PORT
              value:  "8082"
            - name: ORDER_SERVICE_URL
              value:  "order:8080"
            - name: LOG_SERVICE_URL
              value:  "logservice:8083"
            - name: ENV
              value:  "prod"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          
---

apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app:  broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
