apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      containers:
      - name: logservice
        image: "909007/logservice:latest"
        imagePullPolicy:  Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8083
        env:
          - name: APPLICATION_PORT
            value:  "8083"
          - name: DATA_SOURCE_URL
            value:  "mongodb://root:example@host.minikube.internal:27017/"
          - name: ENV
            value:  "prod"



---

apiVersion: v1
kind: Service
metadata:
  name: logservice
  labels:
    app:  logservice
spec:
  selector:
    app: logservice
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
