apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: "909007/order:1.0.0"
          ports:
            - containerPort: 8080
          env:
            - name: APPLICATION_PORT
              value:  "8080"
            - name: PAYMENT_SERVICE_URL
              value:  "payment:8081"
            - name: DATA_SOURCE_URL
              value:  "postgresql://postgres:password@postgres:5432/orders"
            - name: ENV
              value:  "prod"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          
---

apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app:  order
spec:
  selector:
    app: order
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
