

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ExternalName
  externalName: host.docker.internal  # Use the Docker host IP or 'host.docker.internal'
  ports:
    - port: 5672
      targetPort: 5672
      name: test1
    - port: 15672
      targetPort: 15672
      name: test2