version: "3.9"
services:
  db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=orders,payments
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  broker:
    depends_on:
      - db
    build: ../broker/
    restart: always
    ports:
      - "8082:8082"
    environment:
      APPLICATION_PORT: 8082
      ENV: "development"
      ORDER_SERVICE_URL: "order:8080"

  payment:
    depends_on:
      - db
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    build: ../payment/
    restart: always
    environment:
      APPLICATION_PORT: 8081
      ENV: "development"
      DATA_SOURCE_URL: "postgres://postgres:password@db:5432/payments"

  logservice:
    depends_on:
      - db
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    build: ../logservice/
    restart: always
    environment:
      APPLICATION_PORT: 8083
      ENV: "development"
      DATA_SOURCE_URL: "mongodb://root:example@localhost:27017"
  order:
    depends_on:
      - db
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    build: ../order/
    restart: always
    ports:
      - "8080:8080"
    environment:
      APPLICATION_PORT: 8080
      ENV: "development"
      DATA_SOURCE_URL: "postgres://postgres:password@db:5432/orders"
      PAYMENT_SERVICE_URL: "payment:8081"
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo_data:
