CREATE DATABASE IF NOT EXISTS payments;
CREATE DATABASE IF NOT EXISTS orders;

CREATE USER docker;
CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payments TO docker;

CREATE USER docker;
CREATE DATABASE orders;
GRANT ALL PRIVILEGES ON DATABASE orders TO docker;